version: '3'

services:
    api:
        build:
            context: .
            dockerfile: ubuntu.dockerfile
        container_name: api
        ports:
            - 8082:8080
            - 80:80
        volumes:
            - ./:/var/www/html
        environment:
            - POSTGRES_DB=gopos
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - HTTP_URL="0.0.0.0"
            - HTTP_PORT=8080
            - REDIS_PASSWORD=r3d1s@
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - USERS_LIMIT=10
        command: export PATH=$PATH:/usr/local/go/bin
        depends_on:
            - postgres
            - redis
        networks:
          go-studies-network:
            ipv4_address: 172.16.0.2
    
    postgres:
        image: postgres
        restart: always
        container_name: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=gopos
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./dataPgsql/db:/var/lib/postgresql/data
        networks:
            go-studies-network:
                ipv4_address: 172.16.0.3

    redis:
        image: redis:latest
        container_name: redis
        environment:
            - REDIS_PASSWORD=r3d1s@
        command: ["redis-server", "--requirepass", "r3d1s@"]
        ports:
            - "6379:6379"
        networks:
            go-studies-network:
                ipv4_address: 172.16.0.4

networks:
    go-studies-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.16.0.0/16"
