version: '3'

services:
    api:
        build:
            context: .
            dockerfile: ubuntu.dockerfile
        container_name: api
        ports:
            - 8082:8080
            - 80:80
        volumes:
            - ./:/var/www/html
        environment:
            - POSTGRES_DB=gopos
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - HTTP_URL=http://localhost
            - HTTP_PORT=8080
        networks:
          go-studies-network:
            ipv4_address: 172.16.0.2
    
    postgres:
        image: postgres
        restart: always
        container_name: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=gopos
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./dataPgsql/db:/var/lib/postgresql/data
        networks:
            go-studies-network:
                ipv4_address: 172.16.0.3

networks:
    go-studies-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.16.0.0/16"
